# Visualising QH inference tests

Now we have a basic inference run on the QH dataset split up into 3x3x3 voxels, we can put together a pipeline template for creating a .pcd file to visualise everything in CloudCompare.

Let's first combine one of the voxel .pth files with the inference .npy files and produce a .pcd file with that.

In [14]:
import torch
import numpy as np
from pyntcloud import PyntCloud
import pandas as pd

def create_pcd_from_data(pth_file_path, npy_file_path, output_pcd_path):
    # Load data from the .pth file using torch
    data = torch.load(pth_file_path)

    # Load the category data from the .npy file
    categories = np.load(npy_file_path)

    # Convert PyTorch tensors to numpy arrays
    coords = data['coord']#.numpy() if isinstance(data['coord'], torch.Tensor) else data['coord']
    colors = data['color'] #.numpy() if 'color' in data and isinstance(data['color'], torch.Tensor) else None
    normals = data['normal']#.numpy() if 'normal' in data and isinstance(data['normal'], torch.Tensor) else None
    print(coords)
    print(categories)---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[7], line 6
      3 npy_file_path = '/home/sogilvy/Pointcept/exp/test/semseg-pt-v3m1-1-ppt-extreme/result/voxel_1_1_1_pred.npy'
      4 output_pcd_path = '/data/sdd/test.pcd'
----> 6 create_pcd_from_data(pth_file_path, npy_file_path, output_pcd_path)

Cell In[6], line 40, in create_pcd_from_data(pth_file_path, npy_file_path, output_pcd_path)
     37 cloud = PyntCloud(pd.DataFrame(points_dict))
     39 # Save as PCD
---> 40 cloud.to_file(output_pcd_path, as_text=True)

File ~/.cache/pypoetry/virtualenvs/pointcept-1jndxwDi-py3.11/lib/python3.11/site-packages/pyntcloud/core_class.py:174, in PyntCloud.to_file(self, filename, also_save, **kwargs)
    172 ext = filename.split(".")[-1].upper()
    173 if ext not in TO_FILE:
--> 174     raise ValueError(
    175         "Unsupported file format; supported formats are: {}".format(list(TO_FILE)))
    176 kwargs["filename"] = filename
    177 kwargs["points"] = self.points

ValueError: Unsupported file format; supported formats are: ['ASC', 'BIN', 'CSV', 'NPZ', 'OBJ', 'PLY', 'PTS', 'TXT', 'XYZ']
    # Prepare data for PyntCloud
    points_dict = {
        'x': coords[:, 0],
        'y': coords[:, 1],
        'z': coords[:, 2],
        'category': categories
    }
    
    if colors is not None:
        points_dict['red'] = colors[:, 0].astype(np.uint8)
        points_dict['green'] = colors[:, 1].astype(np.uint8)
        points_dict['blue'] = colors[:, 2].astype(np.uint8)

    if normals is not None:
        points_dict['nx'] = normals[:, 0]
        points_dict['ny'] = normals[:, 1]
        points_dict['nz'] = normals[:, 2]

    # Convert dictionary to DataFrame and create PyntCloud object
    cloud = PyntCloud(pd.DataFrame(points_dict))

    # Save as PCD
    cloud.to_file(output_pcd_path)

In [15]:
# Example usage
pth_file_path = '/home/sogilvy/Pointcept/data/qh/val/voxel_1_1_1.pth'
npy_file_path = '/home/sogilvy/Pointcept/exp/test/semseg-pt-v3m1-1-ppt-extreme/result/voxel_1_1_1_pred.npy'
output_pcd_path = '/data/sdd/test.pcd'

create_pcd_from_data(pth_file_path, npy_file_path, output_pcd_path)

[[19.748 22.983  9.988]
 [19.747 22.981 10.025]
 [19.747 22.978 10.073]
 ...
 [19.926 38.092 14.728]
 [19.975 38.091 14.728]
 [20.025 38.09  14.727]]
[0 0 0 ... 0 0 0]


ValueError: Unsupported file format; supported formats are: ['ASC', 'BIN', 'CSV', 'NPZ', 'OBJ', 'PLY', 'PTS', 'TXT', 'XYZ']